//
//  ModelFile.swift
//  USDConverter
//
//  Created by Emma Alyx Wunder on 10.12.19.
//  Copyright © 2019 Emma Alyx Wunder. All rights reserved.
//

import Cocoa
import ModelIO

// confusing aspect: this
class ModelFile {

	let file: URL
	var materials: [ModelMaterial]

	init(modelFile: URL) throws {
		self.file = modelFile
		self.materials = []

		let asset = MDLAsset(url: self.file)

		var childIndex = 1
		for obj in asset.childObjects(of: MDLMesh.self) {
			guard let mesh = obj as? MDLMesh else {
				print("mesh conversion failed")
				continue
			}

			for rawSubmesh in mesh.submeshes ?? [] {
				guard let submesh = rawSubmesh as? MDLSubmesh else {
					print("submesh conversion failed")
					continue
				}

				guard let material = submesh.material else {
					continue
				}

				let materialName = "material_\(childIndex)"

				let mtlMaterial = ModelMaterial(materialName: materialName, originalMaterial: material, assetURL: asset.url)

				self.materials.append(mtlMaterial)
			}

			childIndex += 1
		}
	}

	func generateMTL() -> String {
		var mtlString = "# MTL generated by USDConverter\n\n"
		for material in self.materials {
			mtlString.append(material.generateMTL() + "\n\n")
		}
		return mtlString
	}

}
